import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarDemo } from "@/components/global/sidebar";
import ClientLayout from "@/components/global/clientLayout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Money Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-[#FAF7F0] text-[#FAF7F0] transition-transform overflow-hidden`}
      >
        <main className="h-screen w-screen">
          <ClientLayout children={children} />
        </main>
      </body>
    </html>
  );
}
