# Generated by Django 5.1.4 on 2024-12-23 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_user_alter_budget_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='Budget', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
