# Generated by Django 5.1.4 on 2024-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_budget_end_date_budget_budget_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('transportation', 'Transportation'), ('food', 'Food'), ('healthcare', 'Healthcare'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('debt', 'Debt Payments'), ('savings', 'Savings & Investments'), ('entertainment', 'Entertainment'), ('personal_care', 'Personal Care'), ('clothing', 'Clothing'), ('education', 'Education'), ('gifts_donations', 'Gifts & Donations'), ('children', 'Children'), ('pets', 'Pets'), ('travel', 'Travel'), ('miscellaneous', 'Miscellaneous'), ('business_operations', 'Business Operations'), ('professional_development', 'Professional Development'), ('freelance', 'Freelance Work'), ('taxes', 'Taxes'), ('legal_accounting', 'Legal & Accounting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
