# Generated by Django 5.1.4 on 2024-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_userplaidprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_emoji',
            field=models.CharField(default='💰', max_length=2),
        ),
    ]
