# Generated by Django 5.1.4 on 2024-12-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_amount_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
